- node/django_front/src/components/Navbar.jsx
- node/django_front/src/components/SimpleNavbar.jsx
> create notification icon (#13)

- node/django_front/src/App.js
- node/django_front/src/components/Navbar.jsx
- node/django_front/src/components/SimpleNavbar.jsx
> ナビゲーションバーの色を完成

- node/django_front/src/components/SentPasswordMail.jsx
> パスワード再設定メール送信後の画面

- node/django_front/src/App.js
- node/django_front/src/components/PartTimeAccountSettings.jsx
- node/django_front/src/components/PartTimeSettings.jsx
- node/django_front/src/components/views/RegisterStore.jsx
大和が作った店舗側の設定画面をもとにアルバイト側の設定画面を作成。
変更点は変更可能な要素から店舗側にしかないもの（店舗名・店舗ID等）を削除したのみ。
> アルバイト用の設定画面を作成

- node/django_front/src/components/ShiftSubmit.jsx
> アルバイト側のシフト希望提出画面を追加

- node/django_front/src/components/PartTimeNavbar.jsx
> アルバイト側のナビゲーションバーを追加

- node/django_front/src/components/PartTimeHome.jsx
- node/django_front/src/components/PartTimeShiftList.jsx
> アルバイト側のホーム画面を追加

- node/django_front/src/App.css
- node/django_front/src/components/partTime/BottomNavbar.jsx
> ButtomNavbarを追加

- node/django_front/src/components/partTime/ShiftSubmit.jsx
**チェックボックスはバックエンドかもしれないため、機能しません**
> シフト提出画面に確認画面、チェックボックスを追加

- node/django_front/src/App.js
- node/django_front/src/components/function/SimpleNavbar.jsx
- node/django_front/src/components/partTime/PartTimeRegister.jsx
- node/django_front/src/components/store/Register.jsx
- node/django_front/src/components/store/StoreShiftList.jsx
> コードの細かいところを修正

- requirements.txt
- shiftan/admin.py
Reverts nineteen2021/shiftan-v2#134
> Revert "Feature django update"

- djangopj/settings.py
- node/django_front/src/App.js
- node/django_front/src/components/partTime/PartTimeAccountSettings.jsx
- node/django_front/src/components/store/AccountSettings.jsx
axiosとCORSを使ってReactにDBのデータを表示
idを使って表示するデータを特定するのは未設定
> axiosとCORSを使ってReactにDBのデータを表示

- api/email.py
- api/templates/accounts/activation.html
- api/templates/accounts/confirmation.html
- api/templates/accounts/password_changed_confirmation.html
- api/templates/accounts/password_reset.html
- api/templates/accounts/username_changed_confirmation.html
- api/templates/accounts/username_reset.html
- djangopj/settings.py
- node/django_front/src/App.js
- node/django_front/src/components/function/Activate.jsx
- node/django_front/src/components/partTime/PartTimeRegister.jsx
- node/django_front/src/components/store/Register.jsx
- node/django_front/src/components/store/StoreHome.jsx
- node/django_front/src/components/store/StoreRegister.jsx
- requirements.txt
- shiftan/models.py
- アカウント作成時に送信されるメール処理の追加
- 従業員側のアカウント作成画面と店舗登録画面を分割
- アカウント作成時にAPIでデータベースに追加する処理の追加
- テキストフィールドに適切な値が入力されていないとエラーが出るよう変更
- **Djoserのバージョンを2.1.0→2.0.3に変更**したため、Dockerのコンテナを更新する必要があります
> アカウント登録関連の処理を追加

- node/django_front/src/App.js
- node/django_front/src/components/function/ChangePassword.jsx
- node/django_front/src/components/partTime/PartTimeAccountSettings.jsx
- node/django_front/src/components/store/AccountSettings.jsx
> パスワード変更機能を実装

- node/django_front/src/components/store/ShiftEditorDay.jsx
2パターン試したがうまくいかず、どちらもコメントアウト。
上部はNavigateだけうまく動かず、下部は書き方が不明。どちらかのやり方で行けそう。
> シフト作成画面のスタッフによる画面遷移途中

- node/django_front/src/components/partTime/PartTimeAccountSettings.jsx
- node/django_front/src/components/partTime/PartTimeHome.jsx
- node/django_front/src/components/partTime/PartTimeSettings.jsx
- node/django_front/src/components/store/MakeShift.jsx
- node/django_front/src/components/store/Settings.jsx
- node/django_front/src/components/store/StaffManager.jsx
- node/django_front/src/components/store/StoreHome.jsx
> シフト一覧が上が最新のものになるように実装、各画面にどの画面かわかるよう文字を追加、他

- node/django_front/src/components/partTime/PartTimeAccountSettings.jsx
- node/django_front/src/components/partTime/PartTimeHome.jsx
- node/django_front/src/components/partTime/PartTimeSettings.jsx
- node/django_front/src/components/store/MakeShift.jsx
- node/django_front/src/components/store/Settings.jsx
- node/django_front/src/components/store/StaffManager.jsx
- node/django_front/src/components/store/StoreHome.jsx
主な変更はタイトル通り
その他の変更はコミット履歴を見てください
> シフト一覧が上が最新のものになるように実装、各画面にどの画面かわかるよう文字を追加、他 

- .gitignore
- こんな感じでnode_modules下が追跡されてしまっていたので、gitignoreに追加しました
> gitignoreにnode_modulesを追加

- node/django_front/src/components/store/ShiftEditorDay.jsx
> シフト編集画面で自分が所属していない店舗のシフトにクエリパラメータから飛べないようにする

- node/django_front/src/components/function/ShiftTable.jsx
> shiftTableのバグを修正

- node/django_front/src/components/function/ShiftTable.jsx
> はみ出してるよーん！！！

- node/django_front/src/components/store/StoreRegister.jsx
> 店舗登録画面の「アカウントをお持ちの方はこちら」はいらないのではないかという提案

- node/django_front/src/components/store/Position.jsx
- node/django_front/src/components/store/StaffManager.jsx
> Koki-fore/issue296

- node/django_front/src/components/partTime/PartTimeHome.jsx
- node/django_front/src/components/partTime/PartTimeSettings.jsx
- node/django_front/src/components/partTime/ShiftSubmit.jsx
- node/django_front/src/components/store/MakeShift.jsx
- node/django_front/src/components/store/Management.jsx
- node/django_front/src/components/store/Position.jsx
- node/django_front/src/components/store/Settings.jsx
- node/django_front/src/components/store/ShiftEditorDay.jsx
- node/django_front/src/components/store/StaffManager.jsx
- node/django_front/src/components/store/StoreHome.jsx
店舗・スタッフともに画面左上のパンくずリストを修正
画面のサイズによって文字が隠れてしまう不具合を修正した。
> 画面左上のパンくずリストを修正

- node/django_front/src/components/partTime/PartTimeAccountSettings.jsx
スタッフ側でアカウント情報の更新が不可能になっていた
コミットの中で処理が消えていたため、それを復元した
> Fix staff acount settings

- node/django_front/src/components/function/Activate.jsx
- node/django_front/src/components/function/ChangeColor.jsx
- node/django_front/src/components/function/ChangePassword.jsx
- node/django_front/src/components/function/Login.jsx
- node/django_front/src/components/function/PasswordSentMail.jsx
- node/django_front/src/components/function/ResetPassword.jsx
- node/django_front/src/components/function/ShiftTable.jsx
- node/django_front/src/components/function/endPoint/Create.jsx
- node/django_front/src/components/function/endPoint/Refresh.jsx
- node/django_front/src/components/function/endPoint/Verify.jsx
- node/django_front/src/components/partTime/CheckSubmit.jsx
- node/django_front/src/components/partTime/JoinStore.jsx
- node/django_front/src/components/partTime/PartTimeAccountSettings.jsx
- node/django_front/src/components/partTime/PartTimeHome.jsx
- node/django_front/src/components/partTime/PartTimeRegister.jsx
- node/django_front/src/components/partTime/PartTimeSettings.jsx
- node/django_front/src/components/partTime/ShiftSubmit.jsx
- node/django_front/src/components/store/AccountSettings.jsx
- node/django_front/src/components/store/Certification.jsx
- node/django_front/src/components/store/MakeShift.jsx
- node/django_front/src/components/store/Management.jsx
- node/django_front/src/components/store/Position.jsx
- node/django_front/src/components/store/Register.jsx
- node/django_front/src/components/store/Settings.jsx
- node/django_front/src/components/store/ShiftEditorDay.jsx
- node/django_front/src/components/store/StaffManager.jsx
- node/django_front/src/components/store/StoreHome.jsx
- node/django_front/src/components/store/StoreRegister.jsx
- node/django_front/src/hooks/useAuth.js
axiosで使用されるapiのURLは`REACT_APP_API_URL`という変数名で格納されています。
localhost:8000だったら`REACT_APP_API_URL="http://localhost:8000"`
> axiosのurlをenvファイルから取得するように
